export const ROUTES = {
  login: "/login",
  dashboard: "/dashboard",
  customerSuccess: "/customer-success",
  feedback: "/feedback",
  jobs: "/jobs",
  externalJobs: "/external-jobs",
  candidates: "/candidates",
  users: "/users",
  companies: "/companies",
  schools: "/schools",
  faculties: "/faculties",
  systemHealth: "/system-health",
  account: "/account",
} as const;
